typography_spectrum: 0.2392431595362723
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.66791
  lightness: 0.397416
  rhythmicContrast: 0.620335
  saturation: 0.608269
opengraph: {}
layout_spectrum: 0.594216
analytics: {}
name: PlantBasedCarey
cta: {}
title: Plant Based Whole Food Rocks!
purpose: []
