analytics: {}
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.66791
  lightness: 0.397416
  rhythmicContrast: 0.620335
  saturation: 0.608269
cta: {}
layout_spectrum: 0.594216
name: PlantBasedCarey
opengraph: {}
purpose: []
typography_spectrum: 0.2392431595362723
